inherit_from: configs/final_refinement_params.yaml
dataset:
  input_dir_mesh: "/home/svcl-oowl/brandon/research/Pixel2Mesh/rec_files/pytorch3d_shapenet_renders/02958343/rgba"
  input_dir_img: "data/input_images/pytorch3d_shapenet_renders/02958343/rgba"
  gt_shapes_lst_path: "data/gt_shapes_path_lists/shapenet_02958343_gt_shapes.lst"