inherit_from: configs/final_refinement_params.yaml
dataset:
  input_dir_mesh: "/home/svcl-oowl/brandon/research/CVPR_2021_REFINE/occupancy_networks/out/pytorch3d_renders/03001627/generation/meshes"
  input_dir_img: "data/input_images/pytorch3d_shapenet_renders/03001627/rgba"
  gt_shapes_lst_path: "data/gt_shapes_path_lists/shapenet_03001627_gt_shapes.lst"
  input_poses: "data/perturbed_poses/occnet/03001627/rec_camera_params_perturbed_std_06.pt"