# parameters for test-time optimization
refinement:
  num_iterations: 350
  learning_rate: 0.00007

# loss function parameters
training:
  semantic_dis_lam: 0 # semantic discriminator loss weight 

  img_sym_num_azim: 3 #[1*]
  img_sym_lam: 0 # image-based symmetry loss [75*]

  sil_lam: 10 # silouette loss. [10*]
  vertex_sym_lam: 0.0 # vertex-based symmetry loss [0.0*]

  l2_lam: 0 # l2 loss on delta v  [1*]
  lap_smoothness_lam: 0  # laplacian smoothing loss [10*]
  normal_consistency_lam: 0 # normal consistency loss [10*]

# parameters for the generator and discriminator
semantic_dis_training:
  #dis_weight_path: "out/2020_09_21--07_10_21_job5/semantic_dis_net_weights_99.pt"
  #gen_weight_path: "out/2020_09_21--07_10_21_job5/deform_net_weights_99.pt"
  dis_weight_path: ""
  gen_weight_path: ""
