dataset:
  #input_dir_mesh: "data/test_dataset" # Path to folder with meshes to postprocess.
  #input_dir_img: "data/test_dataset" # Path to folder with images for meshes.
  input_dir_mesh: "data/onet_chair_pix3d_dann_simplified" # Path to folder with meshes to postprocess.
  input_dir_img: "data/img_pix3d_chair/chair" # Path to folder with images for meshes.

brute_force_pose_est:
  num_azims: 20
  num_elevs: 20
  num_dists: 40

model:
  latent_dim_pointnet: 512
  latent_dim_resnet: 256

training:
  num_iterations: 700
  learning_rate: 0.00001 #[0.00001*]

  semantic_dis_num_render: 3
  semantic_dis_lam: 0 # semantic discriminator loss weight

  img_sym_num_azim: 1 #[1*]
  img_sym_lam: 100 # image-based symmetry loss [100*]

  sil_lam: 10 # silouette loss. [5*]
  vertex_sym_lam: 0.1 # vertex-based symmetry loss [0.1*]

  l2_lam: 1 # l2 loss on delta v  [1*]
  lap_lam: 10  # laplacian smoothing loss [10*]
  normals_lam: 10 # normal consistency loss [10*]

  # depreciated
  #semantic_emb_lam: 0
  #semantic_emb_weights_path: data/occnet_pretrained_weights/model_best.pt
  #semantic_emb_cfg_path: occ_uda/configs/domain_adaptation/chair_noDA.yaml
  #semantic_emb_latents_path: occ_uda/chair_noDA_train_latent_vecs.p

semantic_dis_training:
  #real_dataset_dir: "data/semantic_dis/real_renders" # Path to folder with rendered images of real 3d models.
  #fake_dataset_dir: "data/semantic_dis/fake_renders" # Path to folder with rendered images of fake 3d models.
  weight_path: "deformation/semantic_dis_net_weights.pt"
  epochs: 20
  eval_every: 5 # evaluate validation set accuracy every x epochs
