model:
  latent_dim_pointnet: 512
  latent_dim_resnet: 256

training:
  num_iterations: 700
  learning_rate: 0.00001 #[0.00001*]
  img_sym_num_azim: 1 #[3]

  sil_lam: 5 # silouette loss. [5*]
  vertex_sym_lam: 0.1 # vertex-based symmetry loss [0.1*]
  img_sym_lam: 0 # image-based symmetry loss [100*]

  l2_lam: 10 # l2 loss on delta v  [10*]
  lap_lam: 10  # laplacian smoothing loss [10*]
  normals_lam: 10 # normal consistency loss [10*]

  # depreciated
  #semantic_emb_lam: 0
  #semantic_emb_weights_path: data/occnet_pretrained_weights/model_best.pt
  #semantic_emb_cfg_path: occ_uda/configs/domain_adaptation/chair_noDA.yaml
  #semantic_emb_latents_path: occ_uda/chair_noDA_train_latent_vecs.p
