model:
  latent_dim_pointnet: 512
  latent_dim_resnet: 256
training:
  num_iterations: 700

  sil_lam: 5 # silouette loss. [5]
  vertex_sym_lam: 0.1 # vertex-based symmetry loss [0.1*]
  img_sym_lam: 100 # vertex-based symmetry loss [100*]

  l2_lam: 10 # l2 loss on delta v  [10*]
  lap_lam: 10  # laplacian smoothing loss [10*]
  normals_lam: 10 # normal consistency loss [10*]
