dataset:
  input_dir_mesh: "data/onet_chair_pix3d_dann_simplified" # Path to folder with meshes to postprocess.
  input_dir_img: "data/img_pix3d_chair/chair" # Path to folder with images for meshes.


brute_force_pose_est:
  num_azims: 20
  num_elevs: 20
  num_dists: 40

model:
  latent_dim_pointnet: 512
  latent_dim_resnet: 256

training:
  num_iterations: 700
  learning_rate: 0.00001 #[0.00001*]

  semantic_dis_weight_path: "out/2020_08_24--06_45_44_dcgan_dis_drop8/weights_epoch_3.pt"
  semantic_dis_num_render: 3
  semantic_dis_lam: 1 # semantic discriminator loss weight

  img_sym_num_azim: 1 #[1*]
  img_sym_lam: 100 # image-based symmetry loss [100*]

  sil_lam: 10 # silouette loss. [5*]
  vertex_sym_lam: 0.1 # vertex-based symmetry loss [0.1*]

  l2_lam: 1 # l2 loss on delta v  [1*]
  lap_smoothness_lam: 10  # laplacian smoothing loss [10*]
  normal_consistency_lam: 10 # normal consistency loss [10*]

semantic_dis_training:
  real_dataset_dir: "data/semantic_dis_sil/real_renders" # Path to folder with rendered images of real 3d models.
  fake_dataset_dir: "data/semantic_dis_sil/fake_renders" # Path to folder with rendered images of fake 3d models.
  input_dir_pose: "data/onet_chair_pix3d_dann_simplified_processed/pred_poses.p" # path to predicted pose cache dict corresponding to mesh/imgs in input_dir_mesh and input_dir_img
  dataset_meshes_list_path: "data/onet_chair_pix3d_dann_simplified/1502.lst" # path to a file which lists the meshes/imgs to use from input_dir_mesh and input_dir_img. Meshes have to have the same # vertices.

  output_dir: "out" # Path to folder to output saved weights and training pickle
  epochs: 10
  eval_every: 1 # evaluate validation set accuracy every x epochs
  batch_size: 4

  mesh_num_verts: 1502
