inherit_from: configs/test.yaml

semantic_dis_training:
  gen_dir_mesh: "../occupancy_networks/out/pytorch3d_renders/02691156/generation/meshes"
  gen_dir_img: "data/input_images/pytorch3d_shapenet_renders/02691156/rgba"
  #gen_poses: "data/input_images/pytorch3d_shapenet_renders/02691156/rgba/renders_camera_params.pt"
  gen_poses: "../occupancy_networks/out/pytorch3d_renders/02691156/generation/meshes/rec_camera_params.pt"

  dis_class_name: "Airplane"