dataset:
  #input_dir_mesh: "data/onet_chair_shapent_no_DA_simplified" # Path to folder with meshes to postprocess.
  #input_dir_img: "data/img_shapenet_chair" # Path to folder with images for meshes.
  input_dir_mesh: "/home/svcl-oowl/brandon/research/occupancy_networks/out/pytorch3d_renders/03001627/generation/meshes"
  input_dir_img: "data/pytorch3d_shapenet_renders/03001627/rgba"


# parameters for test-time optimization
refinement:
  num_iterations: 350
  learning_rate: 0.00007


# loss function parameters
training:
  semantic_dis_lam: 0 # semantic discriminator loss weight 

  img_sym_num_azim: 1 #[1*]
  img_sym_lam: 75 # image-based symmetry loss [75*]

  sil_lam: 10 # silouette loss. [10*]
  vertex_sym_lam: 0.0 # vertex-based symmetry loss [0.0*]

  l2_lam: 2000 # l2 loss on delta v  [1*]
  lap_smoothness_lam: 10  # laplacian smoothing loss [10*]
  normal_consistency_lam: 10 # normal consistency loss [10*]


# parameters for the generator and discriminator
semantic_dis_training:
  #dis_weight_path: "out/2020_09_21--07_10_21_job5/semantic_dis_net_weights_99.pt"
  #gen_weight_path: "out/2020_09_21--07_10_21_job5/deform_net_weights_99.pt"
  dis_weight_path: ""
  gen_weight_path: ""
