dataset:
  input_dir_mesh: "data/onet_chair_pix3d_no_DA_simplified" # Path to folder with meshes to postprocess.
  input_dir_img: "data/img_pix3d_chair/chair" # Path to folder with images for meshes.


# parameters for test-time optimization
refinement:
  num_iterations: 350
  learning_rate: 0.0001


# loss function parameters
training:
  semantic_dis_lam: 30 # semantic discriminator loss weight 

  img_sym_num_azim: 1 #[1*]
  img_sym_lam: 10 # image-based symmetry loss [75*]

  sil_lam: 100 # silouette loss. [10*]
  vertex_sym_lam: 0.0 # vertex-based symmetry loss [0.0*]

  l2_lam: 1 # l2 loss on delta v  [1*]
  lap_smoothness_lam: 10  # laplacian smoothing loss [10*]
  normal_consistency_lam: 10 # normal consistency loss [10*]


# parameters for the generator and discriminator
semantic_dis_training:
  dis_weight_path: "out/2020_09_21--07_10_21_job5/semantic_dis_net_weights_99.pt"
  gen_weight_path: "out/2020_09_21--07_10_21_job5/deform_net_weights_99.pt"
