inherit_from: configs/test.yaml

refinement:
  num_iterations: 22
  learning_rate: 0.00007


training:
  lap_smoothness_lam: 10  # laplacian smoothing loss [10*]
  normal_consistency_lam: 10 # normal consistency loss [10*]

  l2_lam: 0.1 # l2 loss on delta v  [100*]

  sil_lam: 0 # silouette loss. [10*]
  
  semantic_dis_lam: 10 # semantic discriminator loss weight 


semantic_dis_training:
  dis_weight_path: "out/2020_12_12--11_17_15_job_02/semantic_dis_net_weights_0400.pt"
  gen_weight_path: "out/2020_12_12--11_17_15_job_02/deform_net_weights_0400.pt"