
training:
  num_iterations: 400
  learning_rate: 0.00008 #[0.00001*]

  semantic_dis_num_render: 8
  semantic_dis_lam: 10 # semantic discriminator loss weight

  img_sym_num_azim: 1 #[1*]
  img_sym_lam: 50 # image-based symmetry loss [100*]

  sil_lam: 8 # silouette loss. [5*]
  vertex_sym_lam: 0.1 # vertex-based symmetry loss [0.1*]

  l2_lam: 0.5 # l2 loss on delta v  [1*]
  lap_smoothness_lam: 10  # laplacian smoothing loss [10*]
  normal_consistency_lam: 10 # normal consistency loss [10*]

semantic_dis_training:
  dis_weight_path: ""
  gen_weight_path: ""
  real_dataset_dir: "data/semantic_dis/real_renders" # Path to folder with rendered images of real 3d models.
  real_dataset_dir_sil: "data/semantic_dis_sil/real_renders" # Path to folder with rendered images of real 3d models.

  # for adversarial
  batch_size: 16
  adv_iterations: 3 #10
  dis_epochs_per_iteration: 3 #5
  gen_epochs_per_iteration: 2 #75
  num_batches_gen_train: 10 #30
  save_model_every: 100 # save model every n adversarial iterations
  num_mesh_eval: 10
  label_noise: 0
  real_label_offset: 0.05

  transform_dis_inputs: false
  
  sil_dis_input: true # whether to discirminate between rendered images, or rendered silhouette.
  dis_input_size: 128 # {64, 128, 256}
  randomize_dis_inputs: true
  gen_small_weights_init: false # note: this is overided if gen_weight_path is specified


