dataset:
  input_dir_mesh: "data/test_dataset_one" # Path to folder with meshes to postprocess.
  input_dir_img: "data/test_dataset_one" # Path to folder with images for meshes.

training:
  num_iterations: 450
  learning_rate: 0.00001 #[0.00001*]

  semantic_dis_weight_path: "out/2020_08_24--06_45_44_dcgan_dis_drop8/weights_epoch_3.pt"
  semantic_dis_num_render: 8
  semantic_dis_lam: 100 # semantic discriminator loss weight

  img_sym_num_azim: 1 #[1*]
  img_sym_lam: 100 # image-based symmetry loss [100*]

  sil_lam: 5 # silouette loss. [5*]
  vertex_sym_lam: 0.1 # vertex-based symmetry loss [0.1*]

  l2_lam: 1 # l2 loss on delta v  [1*]
  lap_lam: 10  # laplacian smoothing loss [10*]
  normals_lam: 10 # normal consistency loss [10*]