
# parameters for test-time optimization
refinement:
  num_iterations: 400
  learning_rate: 0.00007

# loss function parameters
training:
  semantic_dis_lam: 1 # semantic discriminator loss weight 

  img_sym_num_azim: 3 #[3*]
  img_sym_lam: 0 # image-based symmetry loss [75*]
  img_sym_bias: 0.0005

  sil_lam: 0 # silouette loss. [10*]
  vertex_sym_lam: 0 # vertex-based symmetry loss [0.0*]
  vertex_sym_bias: 0.0005
  
  vertex_asym: false
  
  l2_lam: 0 # l2 loss on delta v  [100*]
  lap_smoothness_lam: 0  # laplacian smoothing loss [10*]
  normal_consistency_lam: 0 # normal consistency loss [10*]
  
semantic_dis_training:
  # basic setup configs
  cache_dir: "caches"
  use_input_mesh_cache: true
  recompute_input_mesh_cache: false
  save_model_every: 10 # save and evaluate model every n adversarial iterations
  save_samples_every: 5 # save and evaluate samples every n adversarial iterations
  num_mesh_batch_eval: 5
  standardize_num_verts: true
  mesh_num_verts: 1550 #2490
  num_verts_tolerance: 100

  # training details
  batch_size: 8
  epochs: 1000
  D_iter: 5

  adv_iterations: 25000
  dis_steps_per_iteration: 1
  gen_steps_per_iteration: 1

  real_label_offset: 0
  beta1: 0
  lambdaGP: 10

  # generator options
  deform_net_type: "gcn_hybrid_img_input" # {pointnet, gcn_full, fc_vert_aligned, gcn_hybrid, gcn_hybrid_img_input}
  gen_dir_mesh: "../occupancy_networks/out/pytorch3d_renders/04379243/generation/meshes" # table
  gen_dir_img: "data/input_images/pytorch3d_shapenet_renders/04379243/rgba"
  gen_poses: "data/input_images/pytorch3d_shapenet_renders/04379243/rgba/renders_camera_params.pt"
  gen_pointnet_lr: 0.0001
  gen_gcn_lr: 0.0001
  gen_decay: 0.0

  # discriminator options
  dis_type: "points" # type of discriminator input, in {renders, points, multiview}
  dis_real_shapes_dir: "../TreeGAN/datasets/ShapeNet_Benchmark"
  dis_class_name: "Table"
  dis_data_use_cache: True
  dis_data_recompute: False
  dis_data_recreate_cache: False

  # for dis_type = points
  dis_points_lr: 0.0001
  dis_points_decay: 0.0
  dis_points_spectral_norm: True
  dis_points_pooling: "max" # type of pooling to use in pointnet, in {max, avg}

  # for dis_type = multiview
  dis_mv_azims: [0,45,90,135,180,225,270,315]
  dis_mv_dist: 2
  dis_mv_elev: 30
  dis_mv_lighting_mode: "ambient" # in {"ambient", ""}
  dis_mv_render_sil: False
  dis_mv_img_size: 224
  dis_mv_lr: 0.00001
  dis_mv_decay: 0.01
  dis_mv_backbone: "vgg11"

  