
# parameters for test-time optimization
refinement:
  num_iterations: 400
  learning_rate: 0.00007

# loss function parameters
training:
  semantic_dis_lam: 10 # semantic discriminator loss weight 

  img_sym_num_azim: 3 #[3*]
  img_sym_lam: 0 # image-based symmetry loss [75*]
  img_sym_bias: 0.0005

  sil_lam: 0 # silouette loss. [10*]
  vertex_sym_lam: 0 # vertex-based symmetry loss [0.0*]
  vertex_sym_bias: 0.0005
  
  vertex_asym: true
  
  l2_lam: 1 # l2 loss on delta v  [100*]
  lap_smoothness_lam: 10  # laplacian smoothing loss [10*]
  normal_consistency_lam: 10 # normal consistency loss [10*]
  
semantic_dis_training:
  # basic setup configs
  use_input_mesh_cache: true
  recompute_input_mesh_cache: false
  save_model_every: 1 # save and evaluate model every n adversarial iterations
  mesh_num_verts: 642

  # training details
  batch_size: 1
  adv_iterations: 10
  dis_epochs_per_iteration: 5
  gen_epochs_per_iteration: 150
  real_label_offset: 0
  early_stop_dis_acc: -1 # stops training of discriminator early if avg acc of last 10 batches is >= this threshold, in [0,1]. to disable,set to -1

  # generator options
  deform_net_type: "gcn_full" # {pointnet, gcn, gcn_pn, gcn_full, fc_points}
  gen_dir_mesh: "data/adversarial/sphere_points_test/fake_meshes"
  gen_dir_img: "data/adversarial/sphere_points_test/fake_images"
  gen_poses: "data/adversarial/sphere_points_test/poses.p"
  gen_pointnet_lr: 0.00008
  gen_gcn_lr: 0.00007
  gen_decay: 0.0

  # discriminator options
  dis_type: "points" # type of discriminator input, in {renders, points, multiview}
  dis_real_shapes_dir: "data/adversarial/sphere_points_test/real_meshes"
  dis_data_recompute: false
  dis_data_use_cache: True
  dis_data_recreate_cache: True

  # for dis_type = points
  recompute_cache: false
  dis_points_lr: 0.00001
  dis_points_decay: 0.01
  dis_points_encoder: "rgan" # in {pointnet, fc, rgan}

  # for dis_type = multiview
  dis_mv_azims: [0,45,90,135,180,225,270,315]
  dis_mv_dist: 2
  dis_mv_elev: 30
  dis_mv_lighting_mode: "ambient" # in {"ambient", ""}
  dis_mv_render_sil: False
  dis_mv_img_size: 224
  dis_mv_lr: 0.00001
  dis_mv_decay: 0.01
  dis_mv_backbone: "vgg11"

  