inherit_from: configs/asym_ablation_1_params.yaml
dataset:
  input_dir_mesh: "/home/svcl-oowl/brandon/research/occupancy_networks/out/asym_pytorch3d_renders/02828884/generation/meshes"
  input_dir_img: "data/input_images/asym_pytorch3d_shapenet_renders/02828884/rgba"
  gt_shapes_lst_path: "data/gt_shapes_path_lists/shapenet_02828884_gt_shapes.lst"