inherit_from: configs/final_refinement_params.yaml
dataset:
  input_dir_mesh: "/home/svcl-oowl/brandon/research/occupancy_networks/out/pytorch3d_renders/04530566/generation/meshes"
  input_dir_img: "data/input_images/pytorch3d_shapenet_renders/04530566/rgba"
  gt_shapes_lst_path: "data/gt_shapes_path_lists/shapenet_04530566_gt_shapes.lst"