inherit_from: configs/final_refinement_params.yaml
dataset:
  input_dir_mesh: "/home/svcl-oowl/brandon/research/occupancy_networks/out/pix3d/misc/generation/meshes"
  input_dir_img: "data/input_images/pix3d_images_processed_filtered/misc/rgba"
  gt_shapes_lst_path: "data/gt_shapes_path_lists/pix3d_misc_gt_shapes.lst"