inherit_from: configs/test.yaml

training:

  lap_smoothness_lam: 0  # laplacian smoothing loss [10*]
  normal_consistency_lam: 0 # normal consistency loss [10*]

  l2_lam: 0 # l2 loss on delta v  [100*]

  sil_lam: 0 # silouette loss. [10*]
  
  semantic_dis_lam: 1 # semantic discriminator loss weight 


semantic_dis_training:
  gen_dir_mesh: "../occupancy_networks/out/pytorch3d_renders/03001627/generation/meshes"
  gen_dir_img: "data/input_images/pytorch3d_shapenet_renders/03001627/rgba"
  gen_poses: "data/input_images/pytorch3d_shapenet_renders/03001627/rgba/renders_camera_params.pt"

  dis_class_name: "Chair"