inherit_from: configs/ablation_3_params.yaml
dataset:
  input_dir_mesh: "/home/svcl-oowl/brandon/research/occupancy_networks/out/pytorch3d_renders/03001627/generation/meshes"
  input_dir_img: "data/input_images/pytorch3d_shapenet_renders/03001627/rgba"
  gt_shapes_lst_path: "data/gt_shapes_path_lists/shapenet_03001627_gt_shapes.lst"