inherit_from: configs/final_refinement_params.yaml
dataset:
  input_dir_mesh: "/home/svcl-oowl/brandon/research/CVPR_2021_REFINE/occupancy_networks/out/pytorch3d_renders/03001627/generation/meshes"
  input_dir_img: "/home/svcl-oowl/brandon/research/CVPR_2021_REFINE/Pytorch-UNet/test_data/places_MASKED"
  gt_shapes_lst_path: "data/gt_shapes_path_lists/shapenet_03001627_gt_shapes.lst"
  input_poses: "data/predicted_poses/03001627_pred_camera_params.pt"